### ISSUE TITLE
POST /questions

### ISSUE THREAD

**Issue by jasgan** [polymr/polymyr-api#1]
When logged in as a vendor, POSTing to /questions returns an notAuthenticated error:
{
  "error": true,
  "message": "Error notAuthenticated"
}

**Comment by hhanesand** [comment]
I have implemented the `expand` syntax

call
`GET /products?expand=campaign,tags`

to get campaign and tags

**Comment by jasgan** [comment]
^ How do I POST the maker's questions to the API? The call to /questions is still returning a notAuthenticated error.

**Comment by hhanesand** [comment]
ah, my bad - will fix

**Comment by jasgan** [comment]
My POST to /questions still returns the error:

{"error":true,"message":"Error notAuthenticated"}

I POSTed:
{
	"text" : "Does this work?",
	"qualifiers": ["Aesthetics", "Intuitivity", "Ergonomics"],
	"campaign_id" : "41",
	"section_id" : "1"
}

Am I forgetting something lol? Or did you not push the changes to the server yet?

**Comment by hhanesand** [comment]
another issue fixed - its working now
