### ISSUE TITLE
Got Quill.JS Working

### ISSUE THREAD

**Issue by jasgan** [polymr/polymyr-api#11]
Can you create an endpoint that stores this Quill.JS JSON object and store the image as well?

{"ops":[{"attributes":{"bold":true},"insert":"Thanks for the support everyone!"},{"attributes":{"header":2},"insert":"\n"},{"insert":"\n"},{"attributes":{"bold":true},"insert":"Stunning power on a great longboard."},{"attributes":{"header":2},"insert":"\n"},{"insert":"\nImagine 2000 watts (2.6 horsepower) on a 12 lb. longboard. You can do your favorite downhill tricks… going uphill. Or carve and carve… without ever pushing. More time riding and practicing, less time pushing and walking.\n\nWe started with our favorite longboard components, like a Loaded Vanguard, Bear Grizzly 852s, Otang 80A In Heats, and Jehu bearings. While the final product's trucks may change, the rest of those components will be there. We don't believe that adding a motor means compromising your setup.\n\nBoosted Boards feature:\n\nLightweight"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Convenient"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"Fast"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"\nTherefore, it is a necessity in daily life!\n\n"},{"insert":{"image":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAAJ2CAYAAAC9yVGRAAAgAElEQVR4nOy9+5Mc13Xn+Tn3ZmY9+oXGkyApUiQlWiIlWbZkPSxq9JpHxDgcIYc3Juw/YHd/2Zg/aTc2Ytf2rB3jkMcaW7KkkaWhROpBSRTfoECCAEig0e/uqsrHvffsDzezqrrRBKAnAfB+AoXursrKysrMqvzec7/nHFFVJZFIJBKJRCKRuEsx7/QGJBKJRCKRSCQSv02S4E0kEolEIpFI3NUkwZtIJBKJRCKRuKtJgjeRSCQSiUQicVeTBG8ikUgkEolE4q4mCd5EIpFIJBK...........etc."}},{"insert":"\n"}]}

**Comment by hhanesand** [comment]
why can't I just store the json?

**Comment by jasgan** [comment]
Oh LOL I forgot that storing the image is just storing the string. So yeah that works!

**Comment by hhanesand** [comment]
how do you want the upload to be? does multipart work?

**Comment by jasgan** [comment]
yep I think multipart should work!

**Comment by hhanesand** [comment]
ok, you can `PATCH descriptions/{{product_id}}` to upload and `GET descriptions/{{product_id}}` to get the json

both return urls to the files
