### ISSUE TITLE
Labeling Pictures

### ISSUE THREAD

**Issue by jasgan** [polymr/polymyr-api#4]
When POSTing pictures and GETing pictures is it possible to label each image as either the "Thumbnail," "Main Image," Sub Image 1", "Sub Image 2", "Sub Image 3", or "Sub Image 4">

**Comment by hhanesand** [comment]
yeah we can work a system like this in

**Comment by jasgan** [comment]
I think I got a solution for this. Since images are ordered sequentially, could you store Array index 0 to be the Thumbnail, Array index 1 to be the Main Image, Array index 2~5 to be Sub Images?

**Comment by hhanesand** [comment]
done!

**Comment by hhanesand** [comment]
did you want to provide the index yourself when you create the images?
right now i automatically calculate it based on the other images in the database

**Comment by jasgan** [comment]
Yeah, if it's not difficult to implement, that'd be great!

**Comment by hhanesand** [comment]
ok, send ?type=(integer) to mark the images
