### ISSUE TITLE
GET /questions

### ISSUE THREAD

**Issue by jasgan** [polymr/polymyr-api#7]
Since POST /questions didn't work, I created a question in MySQL but when I called GET /questions, it returned:

<html>
    <head>
        <title>502 Bad Gateway</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>502 Bad Gateway</h1>
        </center>
        <hr>
        <center>nginx/1.10.0 (Ubuntu)</center>
    </body>
</html>

**Comment by hhanesand** [comment]
means the server crashed while processing the request
fixed now
