### ISSUE TITLE
Error with polymyr.com

### ISSUE THREAD

**Issue by jasgan** [polymr/polymyr-api#8]
When I login as a vendor on instacrate.co/polymyr/vendor/login.php (GoDaddy's server) it works. But when I login as a vendor on polymyr.com/vendor/login.php I get this error:

"PHP message: PHP Notice:  Undefined variable: content in /home/jasper/polymyr/api/vendors/login.php on line 22
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_substr() in /home/jasper/polymyr/api/vendors/login.php:34
Stack trace:
#0 {main}
  thrown in /home/jasper/polymyr/api/vendors/login.php on line 34" while reading response header from upstream, client: 198.27.199.74, server: polymyr.com, request: "POST /api/vendors/login.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "polymyr.com", re

**Comment by hhanesand** [comment]
No idea what this is, can you google it?

**Comment by jasgan** [comment]
So a few things I know about this error. (1) The form data is successfully sent to the API (2) The API is able to parse and return a message (e.g. if I enter an incorrect password it would tell me). So I think the error is redirecting the vendor from the login page to the vendor dashboard. I googled the error and it said: "You should always refrain from increasing the timeouts, I doubt your backend server response time is the issue here in any case. I got around this issue by clearing the connection keep-alive flag and specifying http version as per the answer here: http://stackoverflow.com/a/36589120/479632" BTW I received the error msg via var/log/nginx sudo cat logs. The browser simply says: "The polymyr.com page isn’t working. polymyr.com is currently unable to handle this request.
HTTP ERROR 500"

**Comment by hhanesand** [comment]
we need to install http://php.net/manual/en/mbstring.installation.php

**Comment by hhanesand** [comment]
I can do it for you

**Comment by hhanesand** [comment]
should be fixed now reopen if not
